language: php
dist: trusty

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install
  - cp phpunit.dist.xml phpunit.xml

script:
  - ./vendor/bin/phpunit